# Generated by Django 2.2.3 on 2019-09-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='content_event',
            options={'verbose_name': 'Content_Event', 'verbose_name_plural': 'Content_Events'},
        ),
        migrations.AlterModelOptions(
            name='content_main_news',
            options={'verbose_name': 'Content_Main_News', 'verbose_name_plural': 'Content_Main_Newss'},
        ),
    ]
